### ISSUE TITLE
Enhancement: Support for TMC2130/TMC2XXX

### ISSUE THREAD

**Issue by felixekman** [Misfittech/nano_stepper#10]
How about a future development of the board to support TMC2130/TMC2XXX series of chips? This would get much quieter running motors plus better micro stepping.

**Comment by clearbucketLabs** [comment]
i think this is acting as it's own driver, does not have a stepper driver as it is one.  it just has a standard H bridge and the MCU does the rest.  you could write interpolation of steps in the firmware in this case from 16 to 256 probably...
