### ISSUE TITLE
commands.cpp compile error.. missing reset.h

### ISSUE THREAD

**Issue by rstager** [Misfittech/nano_stepper#12]
I am getting a compile error on commands.cpp. 

sketch/commands.cpp:7:19: fatal error: reset.h: No such file or directory
 #include "reset.h"

This was changed from Rest.h as part of 874650f, back on Jan 27.

I tried moving back to Reset.h and it worked for me, but I am not sure why the change was made or if this is the best fix.

**Comment by coolio986** [comment]
Changes committed 61cffeb

**Comment by coolio986** [comment]
@trampas, can you close this issue
