### ISSUE TITLE
Wiki Updates

### ISSUE THREAD

**Issue by andrewismoody** [Misfittech/nano_stepper#17]
I forked this repo and created a wiki based on the readme and the other links back to your blog as well as added some stubs for future documentation I plan to add.  Apparently there isn't any way to create a pull request on github for the wiki, so you would have to make the changes from my wiki back to the main branch (I think).  I also wasn't able to add any contributors to my fork, so not sure how you would grab the markdown.
https://github.com/andrewismoody/nano_stepper/wiki

**Comment by coolio986** [comment]
Thanks @andrewismoody
