### ISSUE TITLE
the bug of move motor

### ISSUE THREAD

**Issue by cricket2009** [Misfittech/nano_stepper#19]
My version is "FW: 0.31", stepperDriver is A4954, input signal (STEP, DIR, ENABLE).
      The motor works good for a period of time (such as 2~3 hours), then it fails, The motor rotates fast in one direction,The screen is shown as follows:
![bug](https://user-images.githubusercontent.com/38064527/38293544-7f72d876-381a-11e8-9333-cdf851904385.png)
     after reset, it can works good for a moment(maybe 30 minutes), but then  fails again.
     why is this happening? thanks.

**Comment by coolio986** [comment]
Possible math error using ABS with int32_t and rollover?

**Comment by coolio986** [comment]
Closing, cannot reproduce.
