### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by adamfilip** [Misfittech/nano_stepper#22]
Broken link in Github/website on where to find how to install directions

[Arduino install] (http://misfittech.net/2016/07/27/arduino_install/) for building firmware

**Comment by smeng9** [comment]
Broken link on how to purchase hardware on README.md
[Further Details and to purchase Hardware] (http://misfittech.net/product/nano-zero-stepper/)

**Comment by coolio986** [comment]
Links fixed in d49452a
