### ISSUE TITLE
Ramps 1.4 GRBL

### ISSUE THREAD

**Issue by qiwalker** [Misfittech/nano_stepper#29]
Hi..

can i use GRBL firmware with smart stepper ?
hardaware : Ramps 1.4 + arduino MEGA

Thanks
Rizki

**Comment by coolio986** [comment]
@qiwalker, Yes you can

**Comment by coolio986** [comment]
@trampas, can you close this issue?

**Comment by Misfittech** [comment]
yes it works with GRBL
