### ISSUE TITLE
compile error 'Serial5' was not declared in this scope

### ISSUE THREAD

**Issue by Hellfish78** [Misfittech/nano_stepper#31]
Hi, i'm trying to compile the 0.39 but get this errors:

sketch\commands.cpp: In function 'uint8_t kbhit_hw()':

commands.cpp:1521:9: error: 'Serial5' was not declared in this scope

  return Serial5.available();

         ^

sketch\commands.cpp: In function 'uint8_t getChar_hw()':

commands.cpp:1526:9: error: 'Serial5' was not declared in this scope

  return Serial5.read();

         ^

sketch\commands.cpp: In function 'uint8_t putch_hw(char)':

commands.cpp:1530:9: error: 'Serial5' was not declared in this scope

  return Serial5.write((uint8_t)data);

         ^

exit status 1
sketch\nzs.cpp: In member function 'void NZS::begin()':

nzs.cpp:637:2: error: 'Serial5' was not declared in this scope

  Serial5.begin(SERIAL_BAUD);

  ^

'Serial5' was not declared in this scope

**Comment by tarchive** [comment]
You are missing the Nano Zero board where the Serial5 definition is defined. Either it is not installed or you do not have it selected. 

To install, follow the install guide here. [http://misfittech.net/blog/arduino-package-install/](url)

Once installed "Nano Zero (Native USB Port)" can now be selected from board menu and compilation error Serial5 will be resolved

**Comment by coolio986** [comment]
@Hellfish78 has this been resolved?

**Comment by coolio986** [comment]
Changes committed 98510ac

**Comment by coolio986** [comment]
@trampas, can you close this issue?

**Comment by DanTheHero** [comment]
Please i need to solve this issue

**Comment by coolio986** [comment]
This issue is solved. If you're still having an issue please fill out a bug report.
