### ISSUE TITLE
MKS SERVO 42 ERROR PIN?

### ISSUE THREAD

**Issue by DanTheHero** [Misfittech/nano_stepper#49]
The MKS servo42 have an pin error? I need to know when the stepper have a certain error in other to interrupt my G-Code, but I don't see an error pin or something.

**Comment by vmario89** [comment]
hi,
the docs of Smart Stepper show an error pin which also can be called by USB Serial Interface (e.g. reachable by Linux bash utilizing stty or screen or Windows PuTTY session):
![grafik](https://user-images.githubusercontent.com/5631071/74288444-b3e12d00-4d2c-11ea-9088-2c050c8052db.png)

dont know if Servo42 has the same pins. Maybe ask your question at the mks clone's github repository instead

**Comment by coolio986** [comment]
I do not have a MKS servo 42. If you would like one tested, send us one.
