### ISSUE TITLE
ctrlmode command not working

### ISSUE THREAD

**Issue by Fetzge** [Misfittech/nano_stepper#5]
The ctrlmode command does not set the controller mode correctly.
If I use e.g. ctrlmode 2 sysparams shows 108 for controllerMode and I see undefined symbols on the display (see attached file).
![nzs_ctrlmode](https://cloud.githubusercontent.com/assets/24992637/21752645/8beab9b2-d5dc-11e6-8556-a849d6d5f074.jpeg)

Setting the controllermode via sysparams is working correctly.

**Comment by Misfittech** [comment]
This should be fixed in the latest firmware release of FW0.09  The sysparms are broken out into individual commands,

**Comment by Fetzge** [comment]
But I already used FW0.09. I removed the comments for sysparams, otherwise i wont be able to set the controller mode at all.
![001009](https://cloud.githubusercontent.com/assets/24992637/21865608/2df834ca-d847-11e6-9fef-f1e1535457c5.png)
This is how the commandline looks like.

**Comment by Misfittech** [comment]
I will check in just a bit that controller mode 3 is functional, it might have broke in the build as I normally use the simple mode.

**Comment by Misfittech** [comment]
I have confirmed the bug and I am working on solution now.

**Comment by Misfittech** [comment]
I have pushed a fix (FW 0.10)  for the ctrlmode command which fixes bug of not being able to set the control mode using the command.
