### ISSUE TITLE
Current Homing

### ISSUE THREAD

**Issue by DanTheHero** [Misfittech/nano_stepper#50]
How can I do homing with the current?
In terms of Marlin (Ramps 1.4)

**Comment by coolio986** [comment]
Homing with current is not supported in the current firmware. Homing by angle error is though.

> errorlimit
> Gets set the maximum number of degrees of error that is acceptable, any posistioning error about the error limit will assert the error pin, when error pin is set as error output. For example:
> 
> :>errorlimit 1.8 
> Will set the error limit to 1.8 degrees.

To get this working on Marlin, you will need to talk with Marlin support
