### ISSUE TITLE
2209 question

### ISSUE THREAD

**Issue by froust-company** [Misfittech/nano_stepper#55]
Hi there

I'm looking for change the driver to 2209 on board, can I do this without major firmware modification?

Regards

**Comment by kb-** [comment]
2209 takes STEP/DIR as input signal
A4954 on the Nano Stepper has 4 logical inputs (2 per coil)
It would be a major modification, especially if you want to take advantage of the 2209 functions

**Comment by froust-company** [comment]
Got it, thank you.
