### ISSUE TITLE
add rs485 & modbus

### ISSUE THREAD

**Issue by kidswong999** [Misfittech/nano_stepper#8]
Hello,
The nano_stepper is using tx&rx, so we have to use a main controller (like arduino mega 2560), which owns 3or4 serials  ports.
If we add rs485&modbus into nano_stepper, we could use “daisy chaining”, just 1 serial port in main controller, or one computer could control many servo motors.

how about the idea？ I will make it in my free time.

thank you!

**Comment by kb-** [comment]
The NZS also has I2C. Many NZS can communicate with a controller on the same 2 wires bus.
